/** Drift's own words. Shared chrome (Settings, Sound, Close, What's new, Read aloud) comes from KulibertI18n. */
export const LANGS = ["en", "simple", "uk", "ru", "es", "ar", "fa-AF", "rw", "ti"] as const;
export type Lang = (typeof LANGS)[number];

/** fa-AF, rw, and ti need a native reader. Dari is not Iranian Persian. */
export const NEEDS_NATIVE: Lang[] = ["fa-AF", "rw", "ti"];

export type Key =
  | "slow"
  | "ledeDesk"
  | "ledeTouch"
  | "clouds"
  | "space"
  | "reef"
  | "off"
  | "rain"
  | "bowls"
  | "ocean"
  | "focus"
  | "keys"
  | "soundNote"
  | "watch"
  | "watchOn"
  | "watchHint"
  | "start"
  | "hintDesk"
  | "hintTouch"
  | "whatsBody"
  | "options"
  | "world"
  | "steer"
  | "invertLook"
  | "invertTurn"
  | "night"
  | "wind"
  | "sky"
  | "sun"
  | "stars"
  | "haze"
  | "streaks"
  | "airplanes"
  | "contrails"
  | "throttle"
  | "altimeter"
  | "liveMap"
  | "sight"
  | "sightOff"
  | "sightDot"
  | "sightPlus"
  | "sightRing"
  | "reset"
  | "sensitivity"
  | "soft"
  | "quick"
  | "openOptions"
  | "fast"
  | "slowSpeed"
  | "speed"
  | "flyDesk"
  | "flyTouch"
  | "flySpaceDesk"
  | "flySpaceTouch"
  | "density"
  | "boost"
  | "layerDeep"
  | "layerWorlds"
  | "layerOuter"
  | "layerSurface"
  | "layerAboveReef"
  | "layerShallows"
  | "layerOpen"
  | "layerStrato"
  | "layerAbove"
  | "layerAmong"
  | "layerInside"
  | "liveSky"
  | "listening"
  | "aloft"
  | "radioQuiet"
  | "noRadio";

const EN: Record<Key, string> = {
  slow: "Slow flight",
  ledeDesk: "Three quiet worlds. Glide the clouds, drift past planets, or float above a reef. Pick a calm track, then click and drag to steer.",
  ledeTouch: "Three quiet worlds. Clouds, space, or a reef. Pull the craft, or drag, to steer. Slide the throttle to change speed.",
  clouds: "Clouds",
  space: "Space",
  reef: "Reef",
  off: "Off",
  rain: "Rain",
  bowls: "Bowls",
  ocean: "Ocean",
  focus: "Focus",
  keys: "Keys",
  soundNote: "Rain, waves, and a bowl are calm. Focus and keys are quiet piano.",
  watch: "Watch",
  watchOn: "Watch on",
  watchHint: "Watch levels out and glides. The map stays hidden until you turn Watch off.",
  start: "Start",
  hintDesk: "Click and drag to steer. Scroll or Q and E change speed.",
  hintTouch: "Pull the craft to steer. Throttle is on the right.",
  whatsBody: "Space is a warp of stars you can steer. Hold Boost and they streak.",
  options: "Options",
  world: "World",
  steer: "Steer",
  invertLook: "Invert look",
  invertTurn: "Invert turn",
  night: "Night",
  wind: "Wind",
  sky: "Sky",
  sun: "Sun",
  stars: "Stars",
  haze: "Haze",
  streaks: "Streaks",
  airplanes: "Airplanes",
  contrails: "Contrails",
  throttle: "Throttle",
  altimeter: "Altimeter",
  liveMap: "Live map",
  sight: "Sight",
  sightOff: "No sight",
  sightDot: "Dot sight",
  sightPlus: "Plus sight",
  sightRing: "Ring sight",
  reset: "Reset",
  sensitivity: "Sensitivity",
  soft: "Soft",
  quick: "Quick",
  openOptions: "Open options",
  fast: "Fast",
  slowSpeed: "Slow",
  speed: "Speed",
  flyDesk: "Click and drag to steer. Scroll or drag the throttle to change speed.",
  flyTouch: "Pull the craft or drag to steer. Throttle is on the right.",
  flySpaceDesk: "Drag to steer the stars. Scroll changes speed. Hold Boost or Shift to streak.",
  flySpaceTouch: "Drag to steer. Throttle is on the right. Hold Boost to streak.",
  density: "Density",
  boost: "Boost",
  layerDeep: "Deep space",
  layerWorlds: "Among the worlds",
  layerOuter: "The outer dark",
  layerSurface: "Near the surface",
  layerAboveReef: "Above the reef",
  layerShallows: "The shallows",
  layerOpen: "Open space",
  layerStrato: "The stratosphere",
  layerAbove: "Above the clouds",
  layerAmong: "Among the clouds",
  layerInside: "Inside the clouds",
  liveSky: "Live sky",
  listening: "Listening",
  aloft: "aloft",
  radioQuiet: "Radio quiet",
  noRadio: "No radio",
};

const SIMPLE: Partial<Record<Key, string>> = {
  ledeDesk: "Three quiet places. Clouds, planets, or a reef. Drag to steer.",
  ledeTouch: "Clouds, space, or a reef. Pull to steer. Slide to go faster.",
  keys: "Piano",
  soundNote: "Rain and waves are calm. Focus and keys are quiet piano.",
  watchHint: "Watch flies for you. The map stays off.",
  hintDesk: "Drag to steer. Scroll to change speed.",
  hintTouch: "Pull to steer. Speed is on the right.",
  flyDesk: "Drag to steer. Drag the bar to change speed.",
  flyTouch: "Pull to steer. Speed is on the right.",
  flySpaceDesk: "Drag to steer. Scroll for speed. Hold Boost for long stars.",
  flySpaceTouch: "Drag to steer. Hold Boost for long stars.",
  density: "How many",
  boost: "Boost",
  whatsBody: "Space is fast stars. Hold Boost and they stretch.",
};

const UK: Record<Key, string> = {
  slow: "Повільний політ",
  ledeDesk: "Три тихі світи. Ковзай крізь хмари, повз планети, або над рифом. Обери тихий звук і тягни, щоб керувати.",
  ledeTouch: "Три тихі світи. Хмари, космос або риф. Тягни, щоб керувати. Повзунок змінює швидкість.",
  clouds: "Хмари",
  space: "Космос",
  reef: "Риф",
  off: "Вимкнено",
  rain: "Дощ",
  bowls: "Чаші",
  ocean: "Океан",
  focus: "Фокус",
  keys: "Клавіші",
  soundNote: "Дощ, хвилі і чаша спокійні. Фокус і клавіші — тихе фортепіано.",
  watch: "Дивись",
  watchOn: "Дивись увімкнено",
  watchHint: "Дивись вирівнює політ. Мапа схована, поки не вимкнеш Дивись.",
  start: "Старт",
  hintDesk: "Тягни, щоб керувати. Коліщатко або Q і E змінюють швидкість.",
  hintTouch: "Тягни, щоб керувати. Швидкість справа.",
  whatsBody: "Космос — зоряний ривок. Тримайте Ривок, і зорі витягуються.",
  options: "Опції",
  world: "Світ",
  steer: "Кермо",
  invertLook: "Перевернути погляд",
  invertTurn: "Перевернути поворот",
  night: "Ніч",
  wind: "Вітер",
  sky: "Небо",
  sun: "Сонце",
  stars: "Зорі",
  haze: "Димка",
  streaks: "Смуги",
  airplanes: "Літаки",
  contrails: "Сліди",
  throttle: "Газ",
  altimeter: "Висота",
  liveMap: "Жива мапа",
  sight: "Приціл",
  sightOff: "Без прицілу",
  sightDot: "Крапка",
  sightPlus: "Плюс",
  sightRing: "Кільце",
  reset: "Скинути",
  sensitivity: "Чутливість",
  soft: "М'яко",
  quick: "Швидко",
  openOptions: "Відкрити опції",
  fast: "Швидко",
  slowSpeed: "Повільно",
  speed: "Швидкість",
  flyDesk: "Тягни, щоб керувати. Коліщатко або повзунок змінює швидкість.",
  flyTouch: "Тягни, щоб керувати. Швидкість справа.",
  layerDeep: "Глибокий космос",
  layerWorlds: "Серед світів",
  layerOuter: "Зовнішня темрява",
  layerSurface: "Біля поверхні",
  layerAboveReef: "Над рифом",
  layerShallows: "Мілина",
  layerOpen: "Відкритий космос",
  layerStrato: "Стратосфера",
  layerAbove: "Над хмарами",
  layerAmong: "Серед хмар",
  layerInside: "У хмарах",
  liveSky: "Живе небо",
  listening: "Слухаю",
  aloft: "у небі",
  radioQuiet: "Радіо тихе",
  flySpaceDesk: "Тягни, щоб керувати зорями. Коліщатко змінює швидкість. Тримайте Ривок або Shift — зорі стають смугами.",
  flySpaceTouch: "Тягни, щоб керувати. Повзунок праворуч. Тримайте Ривок — зорі стають смугами.",
  density: "Густота",
  boost: "Ривок",
  noRadio: "Немає радіо",
};

const RU: Record<Key, string> = {
  slow: "Медленный полёт",
  ledeDesk: "Три тихих мира. Скользи сквозь облака, мимо планет или над рифом. Выбери тихий звук и тяни, чтобы рулить.",
  ledeTouch: "Три тихих мира. Облака, космос или риф. Тяни, чтобы рулить. Ползунок меняет скорость.",
  clouds: "Облака",
  space: "Космос",
  reef: "Риф",
  off: "Выкл",
  rain: "Дождь",
  bowls: "Чаши",
  ocean: "Океан",
  focus: "Фокус",
  keys: "Клавиши",
  soundNote: "Дождь, волны и чаша спокойные. Фокус и клавиши — тихое пианино.",
  watch: "Смотреть",
  watchOn: "Смотреть включено",
  watchHint: "Смотреть выравнивает полёт. Карта скрыта, пока не выключишь Смотреть.",
  start: "Старт",
  hintDesk: "Тяни, чтобы рулить. Колёсико или Q и E меняют скорость.",
  hintTouch: "Тяни, чтобы рулить. Скорость справа.",
  whatsBody: "Космос — звёздный рывок. Держи Рывок, и звёзды становятся полосами.",
  options: "Опции",
  world: "Мир",
  steer: "Руль",
  invertLook: "Перевернуть взгляд",
  invertTurn: "Перевернуть поворот",
  night: "Ночь",
  wind: "Ветер",
  sky: "Небо",
  sun: "Солнце",
  stars: "Звёзды",
  haze: "Дымка",
  streaks: "Полосы",
  airplanes: "Самолёты",
  contrails: "Следы",
  throttle: "Газ",
  altimeter: "Высота",
  liveMap: "Живая карта",
  sight: "Прицел",
  sightOff: "Без прицела",
  sightDot: "Точка",
  sightPlus: "Плюс",
  sightRing: "Кольцо",
  reset: "Сброс",
  sensitivity: "Чувствительность",
  soft: "Мягко",
  quick: "Быстро",
  openOptions: "Открыть опции",
  fast: "Быстро",
  slowSpeed: "Медленно",
  speed: "Скорость",
  flyDesk: "Тяни, чтобы рулить. Колёсико или ползунок меняет скорость.",
  flyTouch: "Тяни, чтобы рулить. Скорость справа.",
  layerDeep: "Глубокий космос",
  layerWorlds: "Среди миров",
  layerOuter: "Внешняя тьма",
  layerSurface: "У поверхности",
  layerAboveReef: "Над рифом",
  layerShallows: "Мелководье",
  layerOpen: "Открытый космос",
  layerStrato: "Стратосфера",
  layerAbove: "Над облаками",
  layerAmong: "Среди облаков",
  layerInside: "В облаках",
  liveSky: "Живое небо",
  listening: "Слушаю",
  aloft: "в небе",
  radioQuiet: "Радио тихо",
  flySpaceDesk: "Тяни, чтобы вести звёзды. Колёсико меняет скорость. Держи Рывок или Shift — звёзды тянутся.",
  flySpaceTouch: "Тяни, чтобы рулить. Ползунок справа. Держи Рывок — звёзды тянутся.",
  density: "Плотность",
  boost: "Рывок",
  noRadio: "Нет радио",
};

const ES: Record<Key, string> = {
  slow: "Vuelo lento",
  ledeDesk: "Tres mundos quietos. Flota entre nubes, pasa planetas o nada sobre un arrecife. Elige un sonido calmo y arrastra para girar.",
  ledeTouch: "Tres mundos quietos. Nubes, espacio o un arrecife. Tira para girar. La barra cambia la velocidad.",
  clouds: "Nubes",
  space: "Espacio",
  reef: "Arrecife",
  off: "No",
  rain: "Lluvia",
  bowls: "Cuencos",
  ocean: "Océano",
  focus: "Foco",
  keys: "Teclas",
  soundNote: "Lluvia, olas y un cuenco son calmos. Foco y teclas son piano suave.",
  watch: "Mirar",
  watchOn: "Mirar activo",
  watchHint: "Mirar nivela y flota. El mapa sigue oculto hasta que apagas Mirar.",
  start: "Empezar",
  hintDesk: "Arrastra para girar. La rueda o Q y E cambian la velocidad.",
  hintTouch: "Tira para girar. La velocidad está a la derecha.",
  whatsBody: "El espacio es un campo de estrellas. Mantén Impulso y se estiran.",
  options: "Opciones",
  world: "Mundo",
  steer: "Girar",
  invertLook: "Invertir mirada",
  invertTurn: "Invertir giro",
  night: "Noche",
  wind: "Viento",
  sky: "Cielo",
  sun: "Sol",
  stars: "Estrellas",
  haze: "Bruma",
  streaks: "Rayas",
  airplanes: "Aviones",
  contrails: "Estelas",
  throttle: "Acelerar",
  altimeter: "Altura",
  liveMap: "Mapa en vivo",
  sight: "Mira",
  sightOff: "Sin mira",
  sightDot: "Punto",
  sightPlus: "Cruz",
  sightRing: "Anillo",
  reset: "Reiniciar",
  sensitivity: "Sensibilidad",
  soft: "Suave",
  quick: "Rápido",
  openOptions: "Abrir opciones",
  fast: "Rápido",
  slowSpeed: "Lento",
  speed: "Velocidad",
  flyDesk: "Arrastra para girar. La rueda o la barra cambian la velocidad.",
  flyTouch: "Tira o arrastra para girar. La velocidad está a la derecha.",
  layerDeep: "Espacio profundo",
  layerWorlds: "Entre mundos",
  layerOuter: "La oscuridad exterior",
  layerSurface: "Cerca de la superficie",
  layerAboveReef: "Sobre el arrecife",
  layerShallows: "Agua baja",
  layerOpen: "Espacio abierto",
  layerStrato: "La estratosfera",
  layerAbove: "Sobre las nubes",
  layerAmong: "Entre las nubes",
  layerInside: "Dentro de las nubes",
  liveSky: "Cielo en vivo",
  listening: "Escuchando",
  aloft: "en el aire",
  radioQuiet: "Radio en calma",
  flySpaceDesk: "Arrastra para dirigir las estrellas. La rueda cambia la velocidad. Mantén Impulso o Mayús para estelas.",
  flySpaceTouch: "Arrastra para dirigir. La barra está a la derecha. Mantén Impulso para estelas.",
  density: "Densidad",
  boost: "Impulso",
  noRadio: "Sin radio",
};

const AR: Record<Key, string> = {
  slow: "طيران هادئ",
  ledeDesk: "ثلاثة عوالم هادئة. انزلق بين السحب أو الكواكب أو فوق الشعب. اختر صوتًا هادئًا ثم اسحب لتقود.",
  ledeTouch: "ثلاثة عوالم هادئة. سحب أو فضاء أو شعب. اسحب لتقود. الشريط يغيّر السرعة.",
  clouds: "سحب",
  space: "فضاء",
  reef: "شعب",
  off: "إيقاف",
  rain: "مطر",
  bowls: "طاسات",
  ocean: "محيط",
  focus: "تركيز",
  keys: "مفاتيح",
  soundNote: "المطر والأمواج والطاس هادئة. التركيز والمفاتيح بيانو خافت.",
  watch: "شاهد",
  watchOn: "المشاهدة تعمل",
  watchHint: "شاهد يوازن الطيران. الخريطة تبقى مخفية حتى توقف شاهد.",
  start: "ابدأ",
  hintDesk: "اسحب لتقود. العجلة أو Q و E تغيّر السرعة.",
  hintTouch: "اسحب لتقود. السرعة على اليمين.",
  whatsBody: "الفضاء حقل نجوم سريع. اضغط اندفاع فتمتد النجوم.",
  options: "خيارات",
  world: "عالم",
  steer: "قيادة",
  invertLook: "اعكس النظر",
  invertTurn: "اعكس الدوران",
  night: "ليل",
  wind: "ريح",
  sky: "سماء",
  sun: "شمس",
  stars: "نجوم",
  haze: "ضباب",
  streaks: "خطوط",
  airplanes: "طائرات",
  contrails: "آثار",
  throttle: "سرعة",
  altimeter: "ارتفاع",
  liveMap: "خريطة حية",
  sight: "منظار",
  sightOff: "بلا منظار",
  sightDot: "نقطة",
  sightPlus: "زائد",
  sightRing: "حلقة",
  reset: "إعادة",
  sensitivity: "حساسية",
  soft: "ناعم",
  quick: "سريع",
  openOptions: "افتح الخيارات",
  fast: "سريع",
  slowSpeed: "بطيء",
  speed: "سرعة",
  flyDesk: "اسحب لتقود. العجلة أو الشريط يغيّر السرعة.",
  flyTouch: "اسحب لتقود. السرعة على اليمين.",
  layerDeep: "فضاء عميق",
  layerWorlds: "بين العوالم",
  layerOuter: "الظلام الخارجي",
  layerSurface: "قرب السطح",
  layerAboveReef: "فوق الشعب",
  layerShallows: "الماء الضحل",
  layerOpen: "فضاء مفتوح",
  layerStrato: "الغلاف العالي",
  layerAbove: "فوق السحب",
  layerAmong: "بين السحب",
  layerInside: "داخل السحب",
  liveSky: "سماء حية",
  listening: "أستمع",
  aloft: "في الجو",
  radioQuiet: "الراديو هادئ",
  flySpaceDesk: "اسحب لتوجيه النجوم. العجلة تغيّر السرعة. اضغط اندفاع أو Shift للخطوط.",
  flySpaceTouch: "اسحب للتوجيه. السرعة على اليمين. اضغط اندفاع للخطوط.",
  density: "الكثافة",
  boost: "اندفاع",
  noRadio: "لا راديو",
};

const FA: Record<Key, string> = {
  slow: "پرواز آهسته",
  ledeDesk: "سه دنیای آرام. میان ابرها، کنار سیاره‌ها، یا بالای آبسنگ برو. یک آواز آرام بگیر و برای راندن بکش.",
  ledeTouch: "سه دنیای آرام. ابر، فضا، یا آبسنگ. برای راندن بکش. خط سرعت را عوض می‌کند.",
  clouds: "ابرها",
  space: "فضا",
  reef: "آبسنگ",
  off: "خاموش",
  rain: "باران",
  bowls: "کاسه‌ها",
  ocean: "اقیانوس",
  focus: "تمرکز",
  keys: "کلیدها",
  soundNote: "باران، موج، و کاسه آرام است. تمرکز و کلیدها پیانوی آهسته است.",
  watch: "تماشا",
  watchOn: "تماشا روشن",
  watchHint: "تماشا پرواز را راست می‌کند. نقشه پنهان می‌ماند تا تماشا را خاموش کنی.",
  start: "شروع",
  hintDesk: "برای راندن بکش. چرخ یا Q و E سرعت را عوض می‌کند.",
  hintTouch: "برای راندن بکش. سرعت طرف راست است.",
  whatsBody: "فضا میدان ستاره‌های تند است. شتاب را نگه دار تا کشیده شوند.",
  options: "گزینه‌ها",
  world: "دنیا",
  steer: "راندن",
  invertLook: "نگاه را برعکس کن",
  invertTurn: "چرخش را برعکس کن",
  night: "شب",
  wind: "باد",
  sky: "آسمان",
  sun: "آفتاب",
  stars: "ستاره‌ها",
  haze: "مه",
  streaks: "خط‌ها",
  airplanes: "طیاره‌ها",
  contrails: "ردها",
  throttle: "سرعت",
  altimeter: "بلندی",
  liveMap: "نقشه زنده",
  sight: "نشانه",
  sightOff: "بدون نشانه",
  sightDot: "نقطه",
  sightPlus: "جمع",
  sightRing: "حلقه",
  reset: "از نو",
  sensitivity: "حساسیت",
  soft: "نرم",
  quick: "تند",
  openOptions: "گزینه‌ها را باز کن",
  fast: "تند",
  slowSpeed: "آهسته",
  speed: "سرعت",
  flyDesk: "برای راندن بکش. چرخ یا خط، سرعت را عوض می‌کند.",
  flyTouch: "برای راندن بکش. سرعت طرف راست است.",
  layerDeep: "فضای عمیق",
  layerWorlds: "میان دنیاها",
  layerOuter: "تاریکی بیرون",
  layerSurface: "نزدیک سطح",
  layerAboveReef: "بالای آبسنگ",
  layerShallows: "آب کم",
  layerOpen: "فضای باز",
  layerStrato: "طبقه بلند هوا",
  layerAbove: "بالای ابرها",
  layerAmong: "میان ابرها",
  layerInside: "درون ابرها",
  liveSky: "آسمان زنده",
  listening: "گوش می‌دهم",
  aloft: "در هوا",
  radioQuiet: "رادیو آرام",
  flySpaceDesk: "برای راندن ستاره‌ها بکش. چرخ سرعت را عوض می‌کند. شتاب یا Shift را نگه دار تا خط شوند.",
  flySpaceTouch: "برای راندن بکش. سرعت در راست است. شتاب را نگه دار تا خط شوند.",
  density: "تراکم",
  boost: "شتاب",
  noRadio: "رادیو نیست",
};

const RW: Record<Key, string> = {
  slow: "Kugendesha buhoro",
  ledeDesk: "Isi zitatu zituje. Nyura mu bicu, hafi y'imibumbe, cyangwa hejuru y'urubago. Hitamo ijwi rituje, ukure kugira ngo uyobore.",
  ledeTouch: "Isi zitatu zituje. Ibicu, ikirere, cyangwa urubago. Kura kugira ngo uyobore. Umurongo uhindura umuvuduko.",
  clouds: "Ibicu",
  space: "Ikirere",
  reef: "Urubago",
  off: "Hagarara",
  rain: "Imvura",
  bowls: "Ibikombe",
  ocean: "Inyanja",
  focus: "Itonde",
  keys: "Impine",
  soundNote: "Imvura, amashorongora, n'igikombe bituje. Itonde n'impine ni piyano ito.",
  watch: "Reba",
  watchOn: "Reba irakora",
  watchHint: "Reba iringanya urugendo. Ikarita ibitswe kugeza uhagaritse Reba.",
  start: "Tangira",
  hintDesk: "Kura kugira ngo uyobore. Uruziga cyangwa Q na E bihindura umuvuduko.",
  hintTouch: "Kura kugira ngo uyobore. Umuvuduko uri iburyo.",
  whatsBody: "Ikirere ni inyenyeri zihuta. Fata Kwihuta zikaba imirongo.",
  options: "Amahitamo",
  world: "Isi",
  steer: "Kuyobora",
  invertLook: "Hindura ukureba",
  invertTurn: "Hindura ugana",
  night: "Ijoro",
  wind: "Umuyaga",
  sky: "Ijuru",
  sun: "Izuba",
  stars: "Inyenyeri",
  haze: "Igihuhwe",
  streaks: "Umurongo",
  airplanes: "Indege",
  contrails: "Inzira",
  throttle: "Umuvuduko",
  altimeter: "Uburebure",
  liveMap: "Ikarita ikora",
  sight: "Ikigereranyo",
  sightOff: "Nta kigereranyo",
  sightDot: "Akadomo",
  sightPlus: "Kuraho",
  sightRing: "Uruziga",
  reset: "Subiza",
  sensitivity: "Ubushobozi",
  soft: "Buhoro",
  quick: "Vuba",
  openOptions: "Fungura amahitamo",
  fast: "Vuba",
  slowSpeed: "Buhoro",
  speed: "Umuvuduko",
  flyDesk: "Kura kugira ngo uyobore. Uruziga cyangwa umurongo uhindura umuvuduko.",
  flyTouch: "Kura cyangwa kurura kugira ngo uyobore. Umuvuduko uri iburyo.",
  layerDeep: "Ikirere cyimbitse",
  layerWorlds: "Mu isi",
  layerOuter: "Umwijima wo hanze",
  layerSurface: "Hafi y'hekuru",
  layerAboveReef: "Hejuru y'urubago",
  layerShallows: "Amazi make",
  layerOpen: "Ikirere gifunguye",
  layerStrato: "Ikirere kirekire",
  layerAbove: "Hejuru y'ibicu",
  layerAmong: "Mu bicu",
  layerInside: "Imbere mu bicu",
  liveSky: "Ijuru rikora",
  listening: "Ndumva",
  aloft: "mu kirere",
  radioQuiet: "Radiyo ituje",
  flySpaceDesk: "Kura kugira ngo uyobore inyenyeri. Uruziga ruhindura umuvuduko. Fata Kwihuta cyangwa Shift zigakwirwa.",
  flySpaceTouch: "Kura kugira ngo uyobore. Umuvuduko uri iburyo. Fata Kwihuta zigakwirwa.",
  density: "Ubwuzurane",
  boost: "Kwihuta",
  noRadio: "Nta radiyo",
};

const TI: Record<Key, string> = {
  slow: "ዝንፈስ በረራ",
  ledeDesk: "ሰለስተ ጸጥ ዓለማት። ኣብ ደበና፣ ኣብ ጥቓ ፕላኔታት፣ ወይ ኣብ ልዕሊ ኮራል ኣንሳፍ። ጸጥ ድምጺ ምረጽ፣ ንምምራሕ ስሓብ።",
  ledeTouch: "ሰለስተ ጸጥ ዓለማት። ደበና፣ ህዋ፣ ወይ ኮራል። ንምምራሕ ስሓብ። መስመር ፍጥነት ይቕይር።",
  clouds: "ደበና",
  space: "ህዋ",
  reef: "ኮራል",
  off: "ዕጸው",
  rain: "ዝናብ",
  bowls: "ጽዋታት",
  ocean: "ውቅያኖስ",
  focus: "ትኹረት",
  keys: "መፍትሕ",
  soundNote: "ዝናብ፣ ማዕበል፣ ከምኡውን ጽዋ ጸጥ እዮም። ትኹረትን መፍትሕን ትሑት ፒያኖ እዩ።",
  watch: "ርአ",
  watchOn: "ርአ ተኸፊቱ",
  watchHint: "ርአ በረራ የስተኻኽል። ካርታ ይሕባእ፣ ርአ ክሳብ እተጥፍኦ።",
  start: "ጀምር",
  hintDesk: "ንምምራሕ ስሓብ። መንኰርኰር ወይ Q ከምኡውን E ፍጥነት ይቕይሩ።",
  hintTouch: "ንምምራሕ ስሓብ። ፍጥነት ኣብ የማን እዩ።",
  whatsBody: "ህዋ ፈጣን ኮኾብ እዩ። ምብዝባዝ ሓዝ ኮኾብ ይዝርጋሕ።",
  options: "ምርጫታት",
  world: "ዓለም",
  steer: "ምምራሕ",
  invertLook: "ርኢቶ ግልበጥ",
  invertTurn: "ምዙር ግልበጥ",
  night: "ለይቲ",
  wind: "ንፋስ",
  sky: "ሰማይ",
  sun: "ጸሓይ",
  stars: "ከዋኽብቲ",
  haze: "ጭጋግ",
  streaks: "መስመራት",
  airplanes: "ነፋሪት",
  contrails: "ኣሰር",
  throttle: "ፍጥነት",
  altimeter: "ቁመት",
  liveMap: "ህያው ካርታ",
  sight: "ምልክት",
  sightOff: "ዘይብሉ ምልክት",
  sightDot: "ነጥቢ",
  sightPlus: "መደመር",
  sightRing: "ቀለቤት",
  reset: "መለስ",
  sensitivity: "ስምዒት",
  soft: "ልስሉስ",
  quick: "ቅልጡፍ",
  openOptions: "ምርጫታት ክፈት",
  fast: "ቅልጡፍ",
  slowSpeed: "ዝንፈስ",
  speed: "ፍጥነት",
  flyDesk: "ንምምራሕ ስሓብ። መንኰርኰር ወይ መስመር ፍጥነት ይቕይር።",
  flyTouch: "ንምምራሕ ስሓብ። ፍጥነት ኣብ የማን እዩ።",
  layerDeep: "ዓሚቕ ህዋ",
  layerWorlds: "ኣብ ማእከል ዓለማት",
  layerOuter: "ደጋዊ ጸልማት",
  layerSurface: "ኣብ ጥቓ ሽፋን",
  layerAboveReef: "ኣብ ልዕሊ ኮራል",
  layerShallows: "ሓጺር ማይ",
  layerOpen: "ክፉት ህዋ",
  layerStrato: "ልዑል ኣየር",
  layerAbove: "ኣብ ልዕሊ ደበና",
  layerAmong: "ኣብ ማእከል ደበና",
  layerInside: "ውሽጢ ደበና",
  liveSky: "ህያው ሰማይ",
  listening: "ይሰምዕ",
  aloft: "ኣብ ኣየር",
  radioQuiet: "ሬድዮ ጸጥ",
  flySpaceDesk: "ንምምራሕ ኮኾብ ስሓብ። መንኰርኰር ፍጥነት ይቕይር። ምብዝባዝ ወይ Shift ሓዝ።",
  flySpaceTouch: "ንምምራሕ ስሓብ። ፍጥነት ኣብ የማን። ምብዝባዝ ሓዝ።",
  density: "ጥቕሲ",
  boost: "ምብዝባዝ",
  noRadio: "ሬድዮ የለን",
};

const TABLES: Record<Lang, Partial<Record<Key, string>>> = {
  en: EN,
  simple: SIMPLE,
  uk: UK,
  ru: RU,
  es: ES,
  ar: AR,
  "fa-AF": FA,
  rw: RW,
  ti: TI,
};

const LAYERS: Record<string, Key> = {
  "Deep space": "layerDeep",
  "Among the worlds": "layerWorlds",
  "The outer dark": "layerOuter",
  "Near the surface": "layerSurface",
  "Above the reef": "layerAboveReef",
  "The shallows": "layerShallows",
  "Open space": "layerOpen",
  "The stratosphere": "layerStrato",
  "Above the clouds": "layerAbove",
  "Among the clouds": "layerAmong",
  "Inside the clouds": "layerInside",
};

export function normalizeLang(raw: string | null | undefined): Lang {
  const value = String(raw || "");
  return (LANGS as readonly string[]).includes(value) ? (value as Lang) : "en";
}

export function dirOf(lang: Lang): "rtl" | "ltr" {
  return lang === "ar" || lang === "fa-AF" ? "rtl" : "ltr";
}

export function line(lang: Lang, key: Key): string {
  return TABLES[lang]?.[key] || EN[key] || "";
}

export function layerLine(lang: Lang, english: string): string {
  const key = LAYERS[english];
  return key ? line(lang, key) : english;
}

const SHARED_EN: Record<string, string> = {
  settings: "Settings",
  sound: "Sound",
  close: "Close",
  whatsNew: "What's new",
  readAloud: "Read aloud",
  noVoice: "No voice yet. Read the words.",
};

let sharedReady = false;

/** Shared packs must not change the first paint. The saved door HTML is English. */
export function markSharedReady() {
  sharedReady = true;
}

type I18nApi = { t?: (key: string) => string; ready?: (lang: string, cb: () => void) => void };

export function sharedLine(key: keyof typeof SHARED_EN): string {
  if (sharedReady && typeof window !== "undefined") {
    const api = (window as Window & { KulibertI18n?: I18nApi }).KulibertI18n;
    const value = api?.t?.(key);
    if (value && value !== key) return value;
  }
  return SHARED_EN[key] || "";
}
